"""created passages table

Revision ID: 8a30632b0054
Revises: None
Create Date: 2016-02-16 12:31:15.547048

"""

# revision identifiers, used by Alembic.
revision = '8a30632b0054'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.Column('body_html', sa.UnicodeText(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passages_timestamp'), 'passages', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passages_timestamp'), table_name='passages')
    op.drop_table('passages')
    ### end Alembic commands ###
